import { db } from "@/db"
import { aiGenerations } from "@/db/schema"
import { eq } from "drizzle-orm"

interface GenerateContentParams {
  prompt: string
  type: "website" | "section" | "component" | "content"
  siteId?: string
  language: "en" | "bn"
  userId: string
}

interface GenerationResult {
  content: string
  type: string
  metadata?: Record<string, unknown>
}

export async function generateContent(params: GenerateContentParams): Promise<GenerationResult> {
  const { prompt, type, siteId, language, userId } = params

  // Create generation record
  const [generation] = await db
    .insert(aiGenerations)
    .values({
      userId,
      siteId,
      prompt,
      generationType: type,
      status: "processing",
    })
    .returning()

  try {
    // For now, return a mock response
    // In production, this would call an AI service (OpenAI, Anthropic, etc.)
    const mockContent = generateMockContent(prompt, type, language)

    // Update generation record with result
    await db
      .update(aiGenerations)
      .set({
        result: mockContent,
        status: "completed",
        tokensUsed: Math.floor(Math.random() * 1000) + 100,
      })
      .where(eq(aiGenerations.id, generation.id))

    return {
      content: mockContent,
      type,
      metadata: {
        generationId: generation.id,
        language,
      },
    }
  } catch (error) {
    // Update generation record with error
    await db
      .update(aiGenerations)
      .set({
        status: "failed",
        errorMessage: error instanceof Error ? error.message : "Unknown error",
      })
      .where(eq(aiGenerations.id, generation.id))

    throw error
  }
}

export async function generateImage(prompt: string): Promise<{ url: string }> {
  // Mock image generation
  // In production, this would call an image generation API (DALL-E, Midjourney, etc.)
  return {
    url: `https://placehold.co/800x600/006A4E/ffffff?text=${encodeURIComponent(prompt.slice(0, 20))}`,
  }
}

function generateMockContent(prompt: string, type: string, language: string): string {
  const isBangla = language === "bn"
  
  const templates: Record<string, string> = {
    website: isBangla 
      ? `<!DOCTYPE html>
<html lang="bn">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>আমার ওয়েবসাইট</title>
</head>
<body>
  <header>
    <h1>স্বাগতম</h1>
    <nav>
      <a href="#home">হোম</a>
      <a href="#about">সম্পর্কে</a>
      <a href="#contact">যোগাযোগ</a>
    </nav>
  </header>
  <main>
    <section id="hero">
      <h2>${prompt}</h2>
      <p>আপনার কন্টেন্ট এখানে যাবে</p>
    </section>
  </main>
  <footer>
    <p>© 2024 সর্বস্বত্ব সংরক্ষিত</p>
  </footer>
</body>
</html>`
      : `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Website</title>
</head>
<body>
  <header>
    <h1>Welcome</h1>
    <nav>
      <a href="#home">Home</a>
      <a href="#about">About</a>
      <a href="#contact">Contact</a>
    </nav>
  </header>
  <main>
    <section id="hero">
      <h2>${prompt}</h2>
      <p>Your content goes here</p>
    </section>
  </main>
  <footer>
    <p>© 2024 All rights reserved</p>
  </footer>
</body>
</html>`,
    section: `<section class="py-16">
  <div class="container mx-auto px-4">
    <h2 class="text-3xl font-bold mb-8">${prompt}</h2>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
      <div class="p-6 bg-white rounded-lg shadow">
        <h3 class="text-xl font-semibold mb-4">Feature 1</h3>
        <p class="text-gray-600">Description goes here</p>
      </div>
      <div class="p-6 bg-white rounded-lg shadow">
        <h3 class="text-xl font-semibold mb-4">Feature 2</h3>
        <p class="text-gray-600">Description goes here</p>
      </div>
      <div class="p-6 bg-white rounded-lg shadow">
        <h3 class="text-xl font-semibold mb-4">Feature 3</h3>
        <p class="text-gray-600">Description goes here</p>
      </div>
    </div>
  </div>
</section>`,
    component: `<div class="component">
  <h3>${prompt}</h3>
  <p>Generated component content</p>
</div>`,
    content: isBangla
      ? `# ${prompt}\n\nএই কন্টেন্ট AI দ্বারা তৈরি। আপনার প্রয়োজন অনুযায়ী এডিট করুন।`
      : `# ${prompt}\n\nThis content was generated by AI. Edit it according to your needs.`,
  }

  return templates[type] || templates.content
}
